### ISSUE TITLE
help me!

### ISSUE THREAD

**Issue by sholoomail** [TroJanzHEX/Image-Editor#12]
Hi.
I deploy it in Heroku and see "message_id" error.
I fix it, then my bot was started. But for any filter, I see this error:
'str' object has no attribute 'name'

**Comment by aakash2021-cap** [comment]
> Hi. I deploy it in Heroku and see "message_id" error. I fix it, then my bot was started. But for any filter, I see this error: 'str' object has no attribute 'name'

How you solve the message_id problem

**Comment by MeysamRezazadeh** [comment]
> > Hi. I deploy it in Heroku and see "message_id" error. I fix it, then my bot was started. But for any filter, I see this error: 'str' object has no attribute 'name'
> 
> How you solve the message_id problem

for fixing 'Message' object has no attribute 'message_id': 
change `reply_to_message_id=message.message_id,` to `reply_to_message_id=message.id,` in photo.py and commands.py

and for this error 'str' object has no attribute 'name':
remove `await message.reply_chat_action("upload_photo")` in all edit_.py files

this worked for me :)

**Comment by sholoomail** [comment]
> > > Hi. I deploy it in Heroku and see "message_id" error. I fix it, then my bot was started. But for any filter, I see this error: 'str' object has no attribute 'name'
> > 
> > 
> > How you solve the message_id problem
> 
> for fixing 'Message' object has no attribute 'message_id': change `reply_to_message_id=message.message_id,` to `reply_to_message_id=message.id,` in photo.py and commands.py
> 
> and for this error 'str' object has no attribute 'name': remove `await message.reply_chat_action("upload_photo")` in all edit_.py files
> 
> this worked for me :)

thanks brother.
all filters work except remove bg.
how tp fix it?

**Comment by MeysamRezazadeh** [comment]
works for me!
check your RemoveBG_API

**Comment by sholoomail** [comment]
> works for me! check your RemoveBG_API

FOR "with white bg" works, but for "without bg" not works.

I SEE THIS MESSAGE IN HEROKU LOG:
removebg_plain-error - 'str' object has no attribute 'name'

**Comment by sholoomail** [comment]
ببخشید میتونم تو تلگرام بهتون پیام بدم؟

**Comment by MeysamRezazadeh** [comment]
> 

id: sambyte
